DataBundle\Entity\Movie:
    type: entity
    table: movie
    indexes:
        movie_director_idx:
            columns:
                - movie_director
        movie_owner_idx:
            columns:
                - movie_owner
    id:
        movieId:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: movie_id
            generator:
                strategy: IDENTITY
    fields:
        movieTitle:
            type: string
            nullable: false
            length: 45
            fixed: false
            column: movie_title
        movieSummary:
            type: text
            nullable: false
            length: null
            fixed: false
            column: movie_summary
        movieImage:
            type: text
            nullable: false
            length: null
            fixed: false
            column: movie_image
        movieTrailerCode:
            type: text
            nullable: false
            length: null
            fixed: false
            column: movie_trailer_code
    manyToOne:
        movieOwner:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                movie_owner:
                    referencedColumnName: user_id
            orphanRemoval: false
        movieDirector:
            targetEntity: Director
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                movie_director:
                    referencedColumnName: director_id
            orphanRemoval: false
    manyToMany:
        actor:
            targetEntity: Actor
            cascade: {  }
            mappedBy: null
            inversedBy: movie
            joinTable:
                name: movie_actors
                joinColumns:
                    -
                        name: movie
                        referencedColumnName: movie_id
                inverseJoinColumns:
                    -
                        name: actor
                        referencedColumnName: actor_id
            orderBy: null
        genre:
            targetEntity: Genre
            cascade: {  }
            mappedBy: null
            inversedBy: movie
            joinTable:
                name: movie_genres
                joinColumns:
                    -
                        name: movie
                        referencedColumnName: movie_id
                inverseJoinColumns:
                    -
                        name: genre
                        referencedColumnName: genre_id
            orderBy: null
    lifecycleCallbacks: {  }
